apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-debian
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany  # 修改为只读多访问模式
  gcePersistentDisk:  # 将 hostPath 更改为 gcePersistentDisk
    pdName: new-debian
    fsType: pd-balanced
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-debian
spec:
  storageClassName: standard  # 修改为 standard 存储类
  accessModes:
    - ReadOnlyMany  # 修改为只读多访问模式
  resources:
    requests:
      storage: 20Gi
