apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "fullstack"
        - name: MYSQL_USER
          value: "jerry"
        - name: MYSQL_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: pvc-c39e909b-112b-417f-9406-ac2bc3399562
          mountPath: /var/lib/mysql
      volumes:
      - name: pvc-c39e909b-112b-417f-9406-ac2bc3399562
        persistentVolumeClaim:
          claimName: pvc-demo
