apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: mysql
  labels:
    type: local
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: new-debian
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: mysql
spec:
  storageClassName: mysql-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
