apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany  # 修改为只读多访问模式
  gcePersistentDisk:  # 将 hostPath 更改为 gcePersistentDisk
    pdName: pvc-c39e909b-112b-417f-9406-ac2bc3399562
    fsType: pd-balanced
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: standard  # 修改为 standard 存储类
  accessModes:
    - ReadOnlyMany  # 修改为只读多访问模式
  resources:
    requests:
      storage: 20Gi
